### PR TITLE
282 stop using enums

### PR DESCRIPTION
**Pull request by awong-dev**

### CODE REVIEW

**Comment by awong-dev** [comment]
mu ha ha ha ha ha

**Comment by awong-dev** [comment]
And....with a lot more banging my head against ruby load-logic order, rspec isolation, and understanding domain loads, This finally looks right.

**Comment by emilyville** [comment]
:+1: and some celebratory fireworks!

**Comment by awong-dev** [comment]
Pull back in the fake data generator and readme update. PTAL.

**Comment by awong-dev** [comment]
merging.

**Pull request merged**
