### PR TITLE
Annual eval meets spreadsheet

### PR DESCRIPTION
**Pull request by awong-dev**

### CODE REVIEW

**Comment by awong-dev** [comment]
It's ugly but it's...well...actually...guess it's just ugly.

**Comment by emilyville** [comment]
:+1: 

Once this is merged, I will start a branch to address all of the new elements we're adding in a less ugly way :)

**Comment by awong-dev** [comment]
@emilyville So I told you to hold off merging yesterday because our migrations would collide. Your migration's filename has an earlier timestamp than mine which means it wouldn't get applied if mine was merged first.

_HOWEVER_ I just backdated my file...so now you can merge mine first. :P 

In fact, you should merge mine first now...

**Comment by emilyville** [comment]
Merging!

**Pull request merged**
