### PR TITLE
241 report list all patients

### PR DESCRIPTION
**Pull request by emilyville**
Reports, merged in master
- works for long beach.
- made prettier
- thanks @ShawnArnwine!

### CODE REVIEW

**Comment by emilyville** [comment]
the tests are passing for me locally, with one "pending" I suspect it's due to the changes in capybara, but not sure. @awong-dev maybe you could take a look?

**Comment by awong-dev** [comment]
taking a look

**Comment by awong-dev** [comment]
Rebased and then squished @ShawnArnwine's changes. Then fixed up some bitrot due to domain tabels changes.

UI still need some love, but works again!

**Comment by awong-dev** [comment]
Preemptively merging. Too much in flight.

**Pull request merged**
