### PR TITLE
Add sections to add eval dropdown

### PR DESCRIPTION
**Pull request by huttj**
I tried to make the add evaluation dropdown more readable by adding sections and headers to it.

image

### CODE REVIEW

**Comment by huttj** [comment]
Hm...It fails the tests. I can fix this, but I don't have time to do it right now.

@awong-dev, let me know if you want to use this layout -- if so, I'll modify the tests.

**Comment by awong-dev** [comment]
@emilyville 

I actually like it visually, but the section labels causes a problem with Annual Evaluation. I don't like using acronyms to get around duplicated text. Not sure how to resolve...

**Comment by huttj** [comment]
What about "New AE"?

Or removing the header and changing it to "Annual Evaluation"?

**Comment by iamkevinscott** [comment]
What about using a multi-level top nav structure like below?

screenshot

**Comment by huttj** [comment]
I would prefer not to use nested dropdowns unless the menu  is too large. I generally try to avoid introducing additional clicks into any workflow, wherever possible.

Maybe changing it to "Annual Eval" is enough of a compromise?

**Comment by awong-dev** [comment]
After talking a bunch with the team at long beach, it sees our understanding of these was incorrect. There should only be 3 entries: Annual Evaluation, Acute Rehab, and OMR.  The 90-day/1-year follow ups should be rolled into each of those episodes.

**Comment by huttj** [comment]
Hurrah for keeping it DRY!

**Pull request closed without merging**
