### PR TITLE
add ui and tabigation

### PR DESCRIPTION
**Pull request by emilyville**
addresses issue #339

### CODE REVIEW

**Comment by emilyville** [comment]
TODOs

add fields for 
- [ ] 1 year follow up date
- [ ] 90 day follow up date
- [ ] finish date

other stuff
- [ ] Add new asias to the controller
- [ ] Add ability to create each sub-assessment in the form with unique submit buttons (this is why the tests are currently failing) and then fix the tests

and for probably another pr
- [ ] SWLS

**Comment by awong-dev** [comment]
Rebased on the foundation work cause I think you'll be done first. But here's the start of the fixes to OMR.

**Comment by awong-dev** [comment]
@emilyville oh and before merging...plz fix the PR comment (the first one at the top) so it doesn't say things are borken anymore cuz otherwise that'll end up in our merge history...

**Comment by emilyville** [comment]
Looks good!

**Pull request merged**
