### PR TITLE
Switch over to postgres.

### PR DESCRIPTION
**Pull request by awong-dev**
- Add postgres rake tasks. In particular pg:first_run which
  bootstraps the postgres setup on a development machine.
- Fix db/seeds.rb to correctly handle foreign key relations and
  use iso8601 datesto guarantee postgres can parse the date format.
- Fix migrations to use explicit casts because postgres is more
  string with type information.
- Update the readme to explain how to set up the server.

### CODE REVIEW

**Comment by awong-dev** [comment]
Fixes #13

**Comment by awong-dev** [comment]
@emilyville or @huttj would appreciate code review.

**Comment by emilyville** [comment]
:+1:

**Comment by huttj** [comment]
Looks good to me. Haven't had a chance to test it, though. :wink:

**Comment by awong-dev** [comment]
Thanks!  (BTW, feel free to click merge and delete after the review is done. All long as master stays stable, there's no reason to put a gate keeper mechanism.)

**Pull request merged**
