### PR TITLE
Add Annual Evaluation fields.

### PR DESCRIPTION
**Pull request by awong-dev**
The types are incorrect on a number. We need dropdowns, etc but do not
have values yet. Need to cross-reference with the data dictionary.

### CODE REVIEW

**Comment by awong-dev** [comment]
Implements #6

**Comment by pchunt** [comment]
Types? Not sure what you mean Albert.

**Comment by awong-dev** [comment]
@pchunt 
Basically format and whether the data is an integer, boolean, string, etc. Right now I have everything as free form strings unless they are very _obviously_ dates, integers, or booleans.

It's all in the data dictionary. I just need to cross-reference and update my code. After that, I will be coming to you all for example data to write tests.

**Comment by pchunt** [comment]
Hi Albert,
I wouldn't use or go by the SCIDO dictionary right now. Just populate all the data fields on the spreadsheet I sent you for this shell. Then let the review team go through all these data fields and the navigation features and provide input on what to be included in the final version before fleshing it out. The SCIDO dictionary has way too many redundant and never used data fields, that's why we are not interested in replicating all the data fields according to the SCIDO dictionary. 
Thanks!!!

**Comment by awong-dev** [comment]
@pchunt 

Is the data in the dictionary actually inaccurate? What I was going to do is look at your field...if I had question about the data type/format, then I'd go look in the data dictionary for clarification.

That won't make me add repeated or extra fields.  Or are you saying the data dictionary is actually incorrect when describing a specific field?

**Comment by awong-dev** [comment]
@pchunt 

I filed #30 for this. Will assign to you. Let's move the discussion there.

**Comment by pchunt** [comment]
Can I call you to talk on the phone? Or if you prefer to call me, I am at 562-826-8000 x6113

Peter Cody Hunt, PhD, MPH
Rehabilitation Scientist
Spinal Cord Injury/Disorders Health Care Group
VA Long Beach Healthcare System (07/128)
5901 East 7th Street
Bldg 150, Room R104B
Long Beach, CA 90822
Phone: (562) 826-8000 ext. 6113
Fax: (562) 826-5718
Pager: (562) 683-1590
Email: peter.hunt3@va.gov<mailto:peter.hunt3@va.gov>

**Pull request merged**
